wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: huggingface
    huggingface_version: 4.5.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.8.8
      5: 0.10.30
      6: 4.5.1
      8:
      - 5
batch_size:
  desc: null
  value: 4
encoder_type:
  desc: null
  value: mlp
learning_rate:
  desc: null
  value: 1.0e-06
seed_split:
  desc: null
  value: 13
task:
  desc: null
  value: SST-2
weight_decay:
  desc: null
  value: 0.05
x_input:
  desc: null
  value: mix
